# Generated by Django 5.2 on 2025-04-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flights', '0003_flightbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('transgender', 'TRANSGENDER')])),
                ('passport_no', models.CharField(max_length=50)),
                ('expiry_date', models.DateField()),
                ('passenger_type', models.CharField(choices=[('adult', 'ADULT'), ('child', 'CHILD'), ('infant', 'INFANT')], max_length=50)),
                ('nationality', models.CharField(default='Pakistan', max_length=50)),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='flightbooking',
            name='flight',
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='flight_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('completed', 'COMPLETED'), ('cancelled', 'CANCELLED')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='total_price',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='passengers',
            field=models.ManyToManyField(to='Flights.passenger'),
        ),
        migrations.DeleteModel(
            name='Flight',
        ),
    ]
