# Generated by Django 5.2 on 2025-04-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flights', '0004_passenger_remove_flightbooking_flight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightbooking',
            name='currency',
            field=models.CharField(default='usd'),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='expiry_date',
            field=models.DateField(default='2030-12-31'),
        ),
    ]
